### ISSUE TITLE
Bad output in suckless st with solarized-dark patch

### ISSUE THREAD

**Issue by jmz-b** [ericbn/vim-solarized#1]
vim-solarized looks like [this](http://i.imgur.com/qWJhyT1.png). for comparison [vim-colors-solarized](https://github.com/altercation/vim-colors-solarized) looks like [this](http://i.imgur.com/O3yPkbc.png) 

terminal is suckless st, with st-no_bold_colors-0.6.diff and 
st-solarized-dark-0.6.diff patches from [here](http://st.suckless.org/patches/solarized) applied.

editor is neovim 0.1.5

for what it's worth, [here's ](https://github.com/jmz-b/debian-stterm/tree/rice/debian/patches) my st patch queue

**Comment by ericbn** [comment]
These are the offended highlight groups I could detect from your screenshot:

```
:hi Comment | hi Constant | hi Identifier | hi PreProc | hi Special | hi Statement
```

And this is how they are being defined in ericbn/vim-solarized:

<img width="574" alt="screen shot 2016-11-10 at 7 02 49 am" src="https://cloud.githubusercontent.com/assets/4120606/20176296/1e55f77c-a715-11e6-8aac-31a85388cd42.png">

And in altercation/vim-colors-solarized in my terminal Vim (because `t_Co` is defined as 256):

<img width="574" alt="screen shot 2016-11-10 at 7 03 23 am" src="https://cloud.githubusercontent.com/assets/4120606/20176320/458224d8-a715-11e6-9394-4d3820a987fb.png">

What do you get for running the above command with each colorscheme? What do you get for `:echo &t_Co`?

Now, I'm currently not touching the `term` attributes in ericbn/vim-solarized. Any change by running the command below or adding it to your `.vimrc` after setting the colorscheme?

```
hi Comment term=NONE | hi Constant term=NONE | hi Identifier term=NONE | hi PreProc term=NONE | hi Special term=NONE | hi Statement term=NONE
```

I could get the same distorted colors as in your first screenshot by running `:set t_Co=256` after Vim is initialized...  :- /

Can you get the correct colors after running `:colorscheme solarized`?

**Comment by ericbn** [comment]
@jmz-b, I was not properly setting the `g:colors_name` value, which could have side effects. Could you please check if this fixes your issue?

**Comment by jmz-b** [comment]
Hey man, sorry for ghosting on this issue. i'm not currently using st or nvim for dev. Been given a new machine at work and I haven't bothered ricing yet.

Once things are back to normal with my workstation I'll update.

FYI, i think i recall that shortly after opening this issue, i switched my colorscheme to [flattened](https://github.com/romainl/flattened), which did not seem to have any problems on my setup

**Comment by ericbn** [comment]
Hey, thanks for the heads up! If you get the chance to get back to your suckless st and vim, and try the latest version of this colorscheme again, I'll be happy to get your news on the outcome...
